### ISSUE TITLE
NonDefaultSitePermissions worksheet missing from SMAT Tool

### ISSUE THREAD

**Issue by GayatriChoudhary** [Microsoft/fasttrack-smat-workbook-generator#1]
The SMAT dashboard generator tool which has been modified by SPOAutomation team , was developed on top of SMAT version: Update5_1.0.1711.03001.InternalOnly which includes a new worksheet named NonDefaultSitePermissions. So this new worksheet entry can be seen in scandef.json file.

 
Based on the release note present under fasttrack-smat-workbook-generator release, We observed the link of SMAT tool which is RTW_Update5_1 based on the folder name which got downloaded.
After quickly going through the SMAT->scandef.json file we have not found any entry for the  NonDefaultSitePermission sheet.
 
It seems the released version of SMAT and fasttrack-smat-workbool-generator doesn’t have support the new worksheet which has been added in  Update5_1.0.1711.03001.InternalOnly release. May be because its an internal build. 
For verifying the above we tried to get the respective changes which has been done in SMATDashboard generator which has been released by Automation team, but we found that the two json file which describes the fields mapping named “smat-mappings-2010.json” and “smat-mappings.json” are not present in the release of fasttrack-smat-workbool-generator.

**Comment by patrick-rodgers** [comment]
What is the name of the file and where in the folder structure is it located?

This is a different code base than the previous tool and does not use the configuration files to simplify things.

**Comment by patrick-rodgers** [comment]
This was an issue with confusion around a filename and different versions of SMAT. Closing as non-issue.
